# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leap
baseurl: "/project-leap" # the subpath of your site, e.g. /blog
url: "https://treehouse.github.io" # the base hostname & protocol for your site

sass:
  sass_dir: _sass
  style: compressed

# Speed up Jekyll since we dont need any of the modules
exclude:
    - node_modules
